name: Cooking App CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check HTML
        run: test -f index.html

      - name: Check CSS
        run: test -f style.css

      - name: Check JavaScript
        run: test -f script.js

      - name: Success
        run: echo "Cooking App CI completed successfully!"